modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}" #optional
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "takumicraft" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
updateJSONURL = "https://raw.githubusercontent.com/TNTModders/TakumiCraft_new/master/version/version.json" #optional
displayURL = "https://www.tntmodders.com" #optional
logoFile = "TCLogo.png" #optional
credits = "「ゆかり匠」のテクスチャは野良牛/バファムート氏に製作して頂きました。その他募集MOB多数。" #optional
authors = "${mod_authors}" #optional
description = '''改築にご注意ください。口凸口''' #mandatory
[[dependencies.takumicraft]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.takumicraft]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
